GPB_FILE = "res/table.gbb"
FIELD_TEXTURE =  "res/field.png"
FIELD_NORMAL = "res/fieldNormal.png"
TABLE_TEXTURE = "res/_Wood_Ch.png"
ROOM_TEXTURE = "res/room-baked.png"
OUTSIDE_TEXTURE = "res/outside.png"
BALL_TEXTURE = "res/soccer bake color.png"
BALL_NORMAL = "res/soccerball-normal.png"